# Generated by Django 6.0.6 on 2026-07-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert_photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                (
                    'advert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='adverts.advert',
                        verbose_name='Объявление'
                    )
                ),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', 'uploaded_at'],
                'unique_together': {('advert', 'order')},
            },
        ),
    ]
