# Generated by Django 6.0.6 on 2026-07-10 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                (
                    'category',
                    models.CharField(
                        choices=[('product', 'Товар'), ('service', 'Услуга'), ('event', 'Мероприятие')], max_length=20,
                        verbose_name='Категория'
                    )
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Активно'), ('completed', 'Выполнено/продано'),
                                 ('archived', 'Архивировано')], default='active', max_length=20, verbose_name='Статус'
                    )
                ),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                (
                    'seller',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='adverts',
                        to=settings.AUTH_USER_MODEL, verbose_name='Продавец'
                    )
                ),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
