# Generated by Django 6.0.6 on 2026-07-12 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Чат активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                (
                    'advert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='adverts.advert',
                        verbose_name='Объявление'
                    )
                ),
                (
                    'buyer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chats',
                        to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'
                    )
                ),
                (
                    'seller',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='seller_chats',
                        to=settings.AUTH_USER_MODEL, verbose_name='Продавец'
                    )
                ),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                (
                    'chat',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat',
                        verbose_name='Чат'
                    )
                ),
                (
                    'sender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages',
                        to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'
                    )
                ),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['advert', 'is_active'], name='chats_chat_advert__0767aa_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['buyer', 'is_active'], name='chats_chat_buyer_i_2dd866_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['seller', 'is_active'], name='chats_chat_seller__4c66a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('advert', 'buyer', 'seller')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='chats_messa_chat_id_b17a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chats_messa_sender__b92f58_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chats_messa_is_read_0e2e50_idx'),
        ),
    ]
