# Generated by Django 6.0.6 on 2026-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='flag',
            field=models.CharField(choices=[('to_buyer', 'От продавца'), ('to_seller', 'От покупателя')], max_length=20, verbose_name='Кому адресован'),
        ),
    ]
