# Generated by Django 6.0.6 on 2026-07-12 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                        related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь'
                    )
                ),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'db_table': 'admins',
            },
        ),
    ]
